### ISSUE TITLE
Installation manual

### ISSUE THREAD

**Issue by Squidy06** [Tomas-Mrazek/SmartThings#5]
At first, thanks @Tomas-Mrazek for providing this tool. I started my smart home adventure with fibaro (and I regret it really hard), decided to move to SmartThings. Now I'd to pair my existing fibaro devices to smartthings hub.

Could you please update the Readme, or at least describe it here how to pair Fibaro Heat Controller to SmartThings?

I tried with new (via generic z-wave device, and scan option) and old (via ‘add thing’ option) SmartThings app, but didn’t manage to make it work.

Thank you :)

**Comment by Tomas-Mrazek** [comment]
(Sorry I haven't noticed, copying your response from SmartThigns Community)

> > Generic Z-Wave device is not the correct way.
> > 
> > Via new SmartThings app enable inclusion mode – tap on + (add) -> device -> Scan. Now enable inclusion mode on the TRV itself (quick triple tap with “needle” or “Green” option from menu). It should pair automatically and SmartThings should recognize it as Fibaro Heat Controller. This is also the name of the official DTH. You can check it in Developer Workspace -> My Devices -> {device} -> Type after inclusion.
> > 
> > If you have trouble, make sure you removed any lingering TRV devices from Developer Workspace and you switched TRV to factory settings (“Yellow” option from menu)
> 
>  tried few times this way too, didn’t work. Although I tried one more time and found the issue :slight_smile:
> 
> In case someone will have this problem too. Make sure that your heat controller is correctly resetting to factory defaults. When I’ve been doing this before, after confirming yellow step (to confirm factory reset) nothing was happening. And I thought that was correct behavior - it was not. It should start blinking yellow and you should hear calibration sound.
> 
> After this procedure I managed to pair fibaro heat controller correctly.
